image: Visual Studio 2017
init:
  - git config --global url."https://github.com/".insteadOf "git@github.com:"

configuration:
  - Debug
  - Release

platform:
  - x86
  - x64
  - Any CPU

before_build:
  - dotnet restore
  - ps: |
      write_output env:platform
      $env:platform = ""
      write-output env:platform
build:
  
  
  parallel: true
  project: AdvanceDLSupport.sln

test_script: scripts\appveyor-test.bat

after_test:
  - cmd: scripts\appveyor-coverage.bat
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh
