image: Visual Studio 2017

init:
  - git config --global url."https://github.com/".insteadOf "git@github.com:"
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
configuration:
  - Debug
  - Release
install:
- ps: >-
    $exePath = "$env:TEMP\dotnet-sdk-2.1.4-win-x86.exe"

    (New-Object Net.WebClient).DownloadFile('https://download.microsoft.com/download/1/1/5/115B762D-2B41-4AF3-9A63-92D9680B9409/dotnet-sdk-2.1.4-win-x86.exe', $exePath)

    cmd /c start /wait "$exePath" /install /quiet /norestart

    del $exePath

platform:
  - x86
  - x64
  - Any CPU

before_build:
  - dotnet restore
  #- ps: $env:platform = ""
build:
  
  
  parallel: true
  project: AdvanceDLSupport.sln

test_script: scripts\appveyor-test.bat

after_test:
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - cmd: scripts\appveyor-coverage.bat
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh
