image: Visual Studio 2017

init:
  - git config --global url."https://github.com/".insteadOf "git@github.com:"
  #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
configuration:
  - Debug
  - Release

platform:
  - x86
  - x64
  - Any CPU

before_build:
  - dotnet restore
  #- ps: $env:platform = ""
build:
  
  
  parallel: true
  project: AdvanceDLSupport.sln

test_script: scripts\appveyor-test.bat

after_test:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  - cmd: scripts\appveyor-coverage.bat
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh
